title: Hazel Yu
logo: "/images/headshot.png?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <p align="center">
  <a href="mailto:haazel.y@gmail.com">Email</a> |
  <a href="https://www.linkedin.com/in/hazel-y-51a49721a/">LinkedIn</a> |
    <a href="pdf/Hazel_Yu_Resume.pdf">Resume</a>
  </p>
  
  I have a Master's degree in Data Science from UC Irvine and a BS in Statistics from UC Davis. With a strong passion for data analysis and data science, I am committed to applying my analytical and critical thinking skills to solve complex problems.
   
theme: jekyll-theme-minimal
